version: '3.7'
services:
  mongo-seed:
    environment: 
      DB_HOST: mongo
      DB_NAME: db
      DB_PORT: 27017
      DROP_DATABASE: 'true'
      REPLACE_ID: 'true'
    build:
      context: ./packages/server/docker/env/artifacts/seed
      dockerfile: ./Dockerfile
    image: pkosiec/mongo-seeding
    networks:
      video-technical-test:
    volumes:
      - ./packages/server/docker/env/artifacts/seed/data/:/srv/import-data

  mongo:
    image: mongo:4.0.20@sha256:dd4cbe24eb8233db92b871cc556b77efcc7f9e67bc9516579796d4d08818273e
    networks:
      video-technical-test:
    volumes:
      - mongo_data_db:/data/db
      - mongo_data_config_db:/data/configdb

  client:
    tty: true
    environment:
      PORT: 3000
      NODE_ENV: 'develop'
      CHOKIDAR_USEPOLLING: 'true'
      DEBUG: '*'
    build:
      context: ./packages/client
      dockerfile: ./docker/env/artifacts/client/Dockerfile
      target: development
    image: video-technical-test-client:latest
    networks:
      video-technical-test:
    ports:
      - 9227:9229
      - 3001:3000
    volumes:
      - ./packages/client:/srv/video-technical-test-client
      - node_modules_video-technical-test-client:/srv/video-technical-test-client/node_modules

  server:
    build:
      context: ./packages/server
      dockerfile: ./docker/env/artifacts/server/Dockerfile
      target: development
    image: video-technical-test-server:latest
    networks:
      video-technical-test:
    ports:
      - 9228:9229
      - 3002:80
    volumes:
      - ./packages/server:/srv/video-technical-test-server
      - node_modules_video-technical-test-server:/srv/video-technical-test-server/node_modules

  tests:
    build:
      context: ./packages/server
      dockerfile: ./docker/env/artifacts/server/Dockerfile.test
    networks:
      video-technical-test:

  dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
    command: mongo:27017
    environment:
      - SLEEP_LENGTH=5
      - TIMEOUT_LENGTH=60
    networks:
      video-technical-test:

volumes:
  node_modules_video-technical-test-client:
  node_modules_video-technical-test-server:
  mongo_data_db:
  mongo_data_config_db:

networks:
  video-technical-test:
